"""substrate.kernel.abstractions — frozen contracts layer.

Everything here is a Protocol, pure dataclass, or value type.
No I/O, no concrete implementations, no external dependencies beyond pydantic.
"""

from __future__ import annotations

from substrate.kernel.abstractions.agent.context import (
    CompactionContext,
    CompactionPhase,
    CompactionResult,
    CompactionStrategy,
    ContextBuilder,
    ContextWindow,
)
from substrate.kernel.abstractions.agent.middleware import MiddlewareStage
from substrate.kernel.abstractions.agent.runtime_context import (
    CancellationTokenProtocol,
    RunMeta,
    RunScope,
    scope_of,
)
from substrate.kernel.abstractions.agent.safety import (
    ImageSafetyClassifier,
    SafetyVerdict,
    Severity,
    TextSafetyClassifier,
    max_severity,
)
from substrate.kernel.abstractions.agent.supervision import (
    ExecutionBudget,
    HistoryRetention,
    Priority,
    SpawnBudget,
    Supervision,
)
from substrate.kernel.abstractions.core.content import (
    ChatMessage,
    ContentBlock,
    ContentBlockAdapter,
    DataBlock,
    ErrorBlock,
    JsonObject,
    KernelModel,
    MediaBlock,
    ReasoningBlock,
    Role,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
    UnknownBlock,
    content_blocks_to_str,
    parse_content_block,
)
from substrate.kernel.abstractions.core.error_info import ErrorInfo
from substrate.kernel.abstractions.core.identity import (
    Actor,
    Topic,
)
from substrate.kernel.abstractions.core.trace import TraceContext
from substrate.kernel.abstractions.core.usage import Usage
from substrate.kernel.abstractions.document import (
    DocumentChunk,
    DocumentChunker,
    DocumentExtractor,
    DocumentMetadata,
    DocumentStore,
    ExtractedImage,
    ExtractedImageLabel,
    ExtractedPage,
    ExtractionResult,
)
from substrate.kernel.abstractions.exceptions import (
    AgentCrashError,
    AuthError,
    BlockValidationError,
    BranchAlreadyExistsError,
    BranchHeadConflictError,
    BranchNotFoundError,
    BudgetExhaustedError,
    CancellationError,
    ConcurrentAppendError,
    ContentFilterError,
    ContextLengthError,
    ControlSignal,
    DAGIntegrityError,
    KernelError,
    LeaseLostError,
    MiddlewareTermination,
    NonDeterminismError,
    ObjectNotFoundError,
    OrphanedEffectError,
    PermanentError,
    PolicyTermination,
    RateLimitedError,
    SnapshotConflictError,
    SuspendInterrupt,
    ThreadBusyError,
    TransientError,
    UnsupportedContentError,
)
from substrate.kernel.abstractions.ids import (
    BranchId,
    MessageId,
    TenantId,
    ThreadId,
    UserId,
    new_id,
)
from substrate.kernel.abstractions.llm.llm import (
    EmbeddingClient,
    EmbeddingResult,
    FinishReason,
    GenerationOptions,
    LLMClient,
    LLMResponse,
    Modality,
    ModelCapabilities,
    ReasoningEffort,
)
from substrate.kernel.abstractions.messaging.message import (
    ChatPayload,
    DataPayload,
    Message,
    Payload,
    Subscription,
)
from substrate.kernel.abstractions.messaging.stream import (
    AgentProgress,
    AgentStep,
    CompletionEvent,
    ReasoningDelta,
    StreamDone,
    TextDelta,
)
from substrate.kernel.abstractions.runtime import (
    Agent,
    AgentRunContext,
    AskOutcome,
    Cancel,
    Commit,
    CommitResult,
    Complete,
    DeadLetterEntry,
    DeadLetterReason,
    DeliverResult,
    Delivery,
    Effect,
    EffectResult,
    Fail,
    HeartbeatResult,
    Lease,
    Nack,
    NewEntry,
    Retry,
    RunHandle,
    RunId,
    RunLogEntry,
    RunLogKind,
    RunRecord,
    RunResult,
    RunRetryPolicy,
    RunSpec,
    RunStatus,
    RunStatusSummary,
    RuntimeStore,
    SignalSpec,
    SpawnSpec,
    Spend,
    StoreStats,
    Suspend,
    Wakeup,
    new_run_id,
)
from substrate.kernel.abstractions.storage.blob import BlobStore
from substrate.kernel.abstractions.storage.graph import (
    CypherCapable,
    Entity,
    GraphStore,
    Relationship,
    SubGraph,
)
from substrate.kernel.abstractions.storage.history import (
    Branch,
    HistoryCheckpoint,
    HistoryProvider,
    MessageNode,
)
from substrate.kernel.abstractions.storage.memory import (
    ContextMemoryInjection,
    ExtractionMethod,
    MemoryCategory,
    MemoryMatch,
    MemoryNamespace,
    MemoryProvenance,
    MemoryQuery,
    MemoryRecord,
    MemoryStatus,
    MemoryStore,
    ShortTermMemory,
    TenantWide,
)
from substrate.kernel.abstractions.storage.objects import ObjectStore
from substrate.kernel.abstractions.storage.snapshots import (
    ContentRef,
    WorkspaceFileEntry,
    WorkspaceManifest,
    WorkspaceSnapshot,
    WorkspaceStore,
)
from substrate.kernel.abstractions.storage.tasks import (
    Task,
    TaskList,
    TaskStatus,
    TaskStore,
)
from substrate.kernel.abstractions.storage.vector import (
    Document,
    SearchResult,
    VectorStore,
)
from substrate.kernel.abstractions.tools.approval import (
    ApprovalDecision,
    ApprovalHandler,
    ApprovalRequest,
    ApprovalResult,
)
from substrate.kernel.abstractions.tools.chain import (
    ChainCallRecord,
    ChainFile,
    ChainPolicy,
    ChainRunResult,
    InvocationResult,
)
from substrate.kernel.abstractions.tools.skills import Skill
from substrate.kernel.abstractions.tools.tools import (
    AnyTool,
    HostedTool,
    PayloadBase,
    ProviderDefinedTool,
    Tool,
    ToolCallRequest,
    ToolExecutionResult,
    ToolRegistry,
    ToolRisk,
    ToolType,
    ToolUI,
    is_concurrency_safe,
    is_hosted_tool,
    is_provider_defined_tool,
)

__all__ = [
    # Content
    "JsonObject",
    "Role",
    "KernelModel",
    "MediaBlock",
    "TextBlock",
    "DataBlock",
    "ErrorBlock",
    "ReasoningBlock",
    "ToolUseBlock",
    "ToolResultBlock",
    "UnknownBlock",
    "ChatMessage",
    "ContentBlock",
    "ContentBlockAdapter",
    "parse_content_block",
    "content_blocks_to_str",
    # Exceptions
    "KernelError",
    "ControlSignal",
    "TransientError",
    "PermanentError",
    "PolicyTermination",
    "BlockValidationError",
    "UnsupportedContentError",
    "AgentCrashError",
    "BudgetExhaustedError",
    "MiddlewareTermination",
    "CancellationError",
    "SuspendInterrupt",
    "ConcurrentAppendError",
    "ThreadBusyError",
    "BranchHeadConflictError",
    "SnapshotConflictError",
    "BranchNotFoundError",
    "BranchAlreadyExistsError",
    "DAGIntegrityError",
    "RateLimitedError",
    "ContextLengthError",
    "ContentFilterError",
    "AuthError",
    "LeaseLostError",
    "NonDeterminismError",
    "OrphanedEffectError",
    "ObjectNotFoundError",
    # Identity
    "Actor",
    "Topic",
    "ErrorInfo",
    "TraceContext",
    "TenantId",
    "UserId",
    "ThreadId",
    "BranchId",
    "MessageId",
    "new_id",
    # Supervision
    "Supervision",
    "HistoryRetention",
    "Priority",
    "SpawnBudget",
    "ExecutionBudget",
    # Tools
    "ToolRisk",
    "PayloadBase",
    "ToolType",
    "ToolUI",
    "ToolCallRequest",
    "ToolExecutionResult",
    "Tool",
    "HostedTool",
    "ProviderDefinedTool",
    "AnyTool",
    "is_hosted_tool",
    "is_concurrency_safe",
    "is_provider_defined_tool",
    "ToolRegistry",
    # Payload types
    "ChatPayload",
    "DataPayload",
    "Payload",
    # Messaging
    "Message",
    "Subscription",
    # Skills
    "Skill",
    # LLM
    "GenerationOptions",
    "LLMClient",
    "LLMResponse",
    "EmbeddingClient",
    "EmbeddingResult",
    "Modality",
    "ReasoningEffort",
    "ModelCapabilities",
    "FinishReason",
    "Usage",
    # History
    "HistoryProvider",
    "MessageNode",
    "Branch",
    "HistoryCheckpoint",
    # Context
    "CompactionStrategy",
    "CompactionPhase",
    "CompactionContext",
    "CompactionResult",
    "ContextBuilder",
    "ContextWindow",
    # Middleware
    "MiddlewareStage",
    # Safety
    "Severity",
    "max_severity",
    "SafetyVerdict",
    "TextSafetyClassifier",
    "ImageSafetyClassifier",
    # Token stream
    "TextDelta",
    "ReasoningDelta",
    "CompletionEvent",
    "StreamDone",
    # Progress stream
    "AgentProgress",
    "AgentStep",
    # Object / blob store
    "BlobStore",
    "ObjectStore",
    # Retrieval / RAG knowledge stores
    "Document",
    "SearchResult",
    "VectorStore",
    "Entity",
    "Relationship",
    "SubGraph",
    "GraphStore",
    "CypherCapable",
    # Memory
    "MemoryRecord",
    "MemoryMatch",
    "MemoryCategory",
    "MemoryStatus",
    "MemoryNamespace",
    "MemoryProvenance",
    "ExtractionMethod",
    "MemoryQuery",
    "ContextMemoryInjection",
    "ShortTermMemory",
    "MemoryStore",
    "TenantWide",
    # Tasks
    "Task",
    "TaskList",
    "TaskStatus",
    "TaskStore",
    # Document intelligence & storage
    "DocumentExtractor",
    "DocumentChunker",
    "DocumentStore",
    "DocumentMetadata",
    "DocumentChunk",
    "ExtractedImage",
    "ExtractedImageLabel",
    "ExtractedPage",
    "ExtractionResult",
    # Workspace snapshots
    "ContentRef",
    "WorkspaceFileEntry",
    "WorkspaceManifest",
    "WorkspaceSnapshot",
    "WorkspaceStore",
    # Execution context
    "CancellationTokenProtocol",
    "RunMeta",
    "RunScope",
    "scope_of",
    # HITL
    "ApprovalDecision",
    "ApprovalRequest",
    "ApprovalResult",
    "ApprovalHandler",
    # Chain
    "ChainPolicy",
    "ChainFile",
    "InvocationResult",
    "ChainCallRecord",
    "ChainRunResult",
    # Durable runtime contracts
    "RunId",
    "RunStatus",
    "new_run_id",
    "RunLogEntry",
    "RunLogKind",
    "Effect",
    "EffectResult",
    "DeadLetterReason",
    "DeadLetterEntry",
    "Wakeup",
    "RunRetryPolicy",
    "RunHandle",
    "RunResult",
    "AgentRunContext",
    "Agent",
    "AskOutcome",
    "RunStatusSummary",
    "Cancel", "Commit", "CommitResult", "Complete", "DeliverResult", "Delivery", "Fail",
    "HeartbeatResult", "Lease", "Nack", "NewEntry", "Retry", "RunRecord", "RunSpec",
    "RuntimeStore", "SignalSpec", "SpawnSpec", "Spend", "StoreStats", "Suspend",
]
