"""substrate.types — Value types every part of the engine shares: content blocks, messages, ids, usage, errors, run scope."""

from __future__ import annotations

from substrate.types.content import (
    ChatMessage,
    ContentBlock,
    ContentBlockAdapter,
    DataBlock,
    ErrorBlock,
    JsonObject,
    KernelModel,
    MediaBlock,
    ReasoningBlock,
    Role,
    TextBlock,
    ToolResultBlock,
    ToolUseBlock,
    UnknownBlock,
    content_blocks_to_str,
    parse_content_block,
)
from substrate.types.error_info import (
    ErrorInfo,
)
from substrate.types.errors import (
    AgentCrashError,
    AuthError,
    BlockValidationError,
    BranchAlreadyExistsError,
    BranchHeadConflictError,
    BranchNotFoundError,
    BudgetExhaustedError,
    CancellationError,
    ConcurrentAppendError,
    ContentFilterError,
    ContextLengthError,
    ControlSignal,
    DAGIntegrityError,
    KernelError,
    LeaseLostError,
    MiddlewareTermination,
    NonDeterminismError,
    ObjectNotFoundError,
    OrphanedEffectError,
    PermanentError,
    PolicyTermination,
    RateLimitedError,
    SnapshotConflictError,
    SuspendInterrupt,
    ThreadBusyError,
    TransientError,
    UnsupportedContentError,
)
from substrate.types.identity import (
    Actor,
    Topic,
)
from substrate.types.ids import (
    BranchId,
    MessageId,
    TenantId,
    ThreadId,
    UserId,
    new_id,
)
from substrate.types.run import (
    CancellationTokenProtocol,
    RunMeta,
    RunScope,
    scope_of,
)
from substrate.types.run_log import (
    RunLogEntry,
    RunLogKind,
)
from substrate.types.run_status import (
    RunId,
    RunStatus,
    new_run_id,
)
from substrate.types.scope import (
    Scope,
)
from substrate.types.stream import (
    AgentProgress,
    AgentStep,
    CompletionEvent,
    ReasoningDelta,
    StreamDone,
    TextDelta,
)
from substrate.types.supervision import (
    ExecutionBudget,
    HistoryRetention,
    Priority,
    SpawnBudget,
    Supervision,
)
from substrate.types.trace import (
    TraceContext,
)
from substrate.types.usage import (
    Usage,
)
from substrate.types.wakeup import (
    Wakeup,
)

__all__ = [
    "Actor",
    "AgentCrashError",
    "AgentProgress",
    "AgentStep",
    "AuthError",
    "BlockValidationError",
    "BranchAlreadyExistsError",
    "BranchHeadConflictError",
    "BranchId",
    "BranchNotFoundError",
    "BudgetExhaustedError",
    "CancellationError",
    "CancellationTokenProtocol",
    "ChatMessage",
    "CompletionEvent",
    "ConcurrentAppendError",
    "ContentBlock",
    "ContentBlockAdapter",
    "ContentFilterError",
    "ContextLengthError",
    "ControlSignal",
    "DAGIntegrityError",
    "DataBlock",
    "ErrorBlock",
    "ErrorInfo",
    "ExecutionBudget",
    "HistoryRetention",
    "JsonObject",
    "KernelError",
    "KernelModel",
    "LeaseLostError",
    "MediaBlock",
    "MessageId",
    "MiddlewareTermination",
    "NonDeterminismError",
    "ObjectNotFoundError",
    "OrphanedEffectError",
    "PermanentError",
    "PolicyTermination",
    "Priority",
    "RateLimitedError",
    "ReasoningBlock",
    "ReasoningDelta",
    "Role",
    "RunId",
    "RunLogEntry",
    "RunLogKind",
    "RunMeta",
    "RunScope",
    "RunStatus",
    "Scope",
    "SnapshotConflictError",
    "SpawnBudget",
    "StreamDone",
    "Supervision",
    "SuspendInterrupt",
    "TenantId",
    "TextBlock",
    "TextDelta",
    "ThreadBusyError",
    "ThreadId",
    "ToolResultBlock",
    "ToolUseBlock",
    "Topic",
    "TraceContext",
    "TransientError",
    "UnknownBlock",
    "UnsupportedContentError",
    "Usage",
    "UserId",
    "Wakeup",
    "content_blocks_to_str",
    "new_id",
    "new_run_id",
    "parse_content_block",
    "scope_of",
]
