"""Stream events — what an agent shows the world while it works.

Two independent channels:

1. **Token stream** (``TextDelta``, ``ReasoningDelta``, ``CompletionEvent``,
   ``StreamDone``) — the LLM's output as it is generated by the agent currently
   speaking. Live, ephemeral, not part of replay state.

2. **Progress stream** (``AgentProgress``) — structured step events from every
   agent in the supervision tree. ``agent_id``, ``parent_id`` and ``depth`` let a
   consumer rebuild the hierarchy from one subscription.

Every event carries a ``seq`` that increases within a run, so a consumer can
reorder events a transport delivered out of order; ``agent_id`` and ``run_id``
demultiplex concurrent streams. These are pure data types — transport (SSE,
WebSocket, console) lives above the kernel.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import StrEnum

from pydantic import BaseModel, Field

from substrate.types.content import ContentBlock
from substrate.types.finish_reason import FinishReason
from substrate.types.identity import Actor
from substrate.types.usage import Usage

# ---------------------------------------------------------------------------
# Token stream events  (LLM output, token by token)
# ---------------------------------------------------------------------------


class TextDelta(BaseModel):
    """Incremental text content — emitted token-by-token."""

    text: str
    agent_id: Actor | None = None
    run_id: str = ""
    seq: int = 0

    model_config = {"frozen": True, "arbitrary_types_allowed": True}


class ReasoningDelta(BaseModel):
    """Incremental reasoning / thinking trace — emitted as the model thinks."""

    text: str
    agent_id: Actor | None = None
    run_id: str = ""
    seq: int = 0

    model_config = {"frozen": True, "arbitrary_types_allowed": True}


class CompletionEvent(BaseModel):
    """Final token-stream event — carries the fully assembled response."""

    content: list[ContentBlock]
    usage: Usage = Field(default_factory=Usage)
    finish_reason: FinishReason = FinishReason.UNSPECIFIED
    response_id: str | None = None
    served_model: str | None = None
    metadata: dict[str, str] = Field(default_factory=dict)
    agent_id: Actor | None = None
    run_id: str = ""
    seq: int = 0

    model_config = {"frozen": True, "arbitrary_types_allowed": True}


class StreamDone(BaseModel):
    """End-of-token-stream sentinel. Consumers stop on receipt."""

    reason: str = "complete"

    model_config = {"frozen": True}


# ---------------------------------------------------------------------------
# Progress events  (supervision tree, every agent at every step)
# ---------------------------------------------------------------------------


class AgentStep(StrEnum):
    """Standard agent progress step names.

    Using ``StrEnum`` ensures ``AgentProgress.step`` is always a known
    value and enables exhaustive matching in consumers.
    """

    STARTED = "started"
    THINKING = "thinking"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    HANDOFF = "handoff"
    PAUSED = "paused"
    DONE = "done"
    ERROR = "error"


class AgentProgress(BaseModel):
    """Structured progress event emitted by every agent at every step.

    One run shares a single progress stream across all agents in the tree. The ``agent_id``,
    ``parent_id``, and ``depth`` fields let the UI reconstruct the hierarchy
    from a single subscription.

    ``seq`` is strictly increasing within one run so subscribers can detect
    gaps and reorder out-of-order deliveries from pub/sub transports.

    ``ts`` is the emission wall-clock time (UTC). Use for display only;
    use ``seq`` for ordering.
    """

    agent_id: Actor
    step: AgentStep
    content: str
    run_id: str = ""
    parent_id: Actor | None = None
    depth: int = 0
    seq: int = 0
    ts: datetime = Field(default_factory=lambda: datetime.now(tz=timezone.utc))
    metadata: dict[str, str] = Field(default_factory=dict)

    model_config = {"frozen": True, "arbitrary_types_allowed": True}


__all__ = [
    "TextDelta",
    "ReasoningDelta",
    "CompletionEvent",
    "StreamDone",
    "AgentProgress",
    "AgentStep",
]
